/* file_name : touch_ioctl.h
 *
 * description : To integrate TOUCH_IOCTL FLAGS targeting EF33series , EF39series
 *
 */

#ifndef _TOUCH_IOCTL_H_
#define _TOUCH_IOCTL_H_

typedef enum {	
#if defined(CONFIG_MACH_MSM8X60_EF39S)||defined(CONFIG_MACH_MSM8X60_EF40S)||defined(CONFIG_MACH_MSM8X60_EF40K)||defined(CONFIG_MACH_MSM8X60_EF65L)
    GET_TOUCH_ID = 101,
    APPLY_TOUCH_CONFIG = 501,
    DIAG_DEBUG,
    RESET_TOUCH_CONFIG,
    GET_TOUCH_CONFIG,
    SET_TOUCH_CONFIG,
    READ_ITO_TYPE,
    TOUCH_DEBUG,
    GET_REFERENCE_DATA,
    CALIBRATE,
#endif

	TOUCH_IOCTL_READ_LASTKEY=1001,	
	TOUCH_IOCTL_DO_KEY,	
	TOUCH_IOCTL_RELEASE_KEY, 
	TOUCH_IOCTL_CLEAN,
	TOUCH_IOCTL_DEBUG,
	TOUCH_IOCTL_RESTART,
	TOUCH_IOCTL_PRESS_TOUCH,
	TOUCH_IOCTL_RELEASE_TOUCH,
	TOUCH_IOCTL_CHARGER_MODE,
	TOUCH_IOCTL_POWER_OFF,
    TOUCH_IOCTL_STYLUS_MODE,
    TOUCH_IOCTL_CALIBRATE,
#if defined(CONFIG_MACH_MSM8X60_EF39S)||defined(CONFIG_MACH_MSM8X60_EF40S)||defined(CONFIG_MACH_MSM8X60_EF40K)||defined(CONFIG_MACH_MSM8X60_EF65L)
    TOUCH_CALL_MODE_ENABLE = 1013,
    TOUCH_CALL_MODE_DISABLE = 1014,
#endif

    TOUCH_IOCTL_DISABLE_DEBUG = 1100,
    TOUCH_IOCTL_ENABLE_DEBUG,

	TOUCH_IOCTL_DELETE_ACTAREA = 2001,
	TOUCH_IOCTL_RECOVERY_ACTAREA,

	TOUCH_IOCTL_SENSOR_X = 2005,
	TOUCH_IOCTL_SENSOR_Y,
	TOUCH_IOCTL_CHECK_BASE,
	TOUCH_IOCTL_READ_IC_VERSION,
#if defined(CONFIG_MACH_MSM8X60_EF33S)||defined(CONFIG_MACH_MSM8X60_EF34C)||defined(CONFIG_MACH_MSM8X60_EF34K)||defined(CONFIG_MACH_MSM8X60_EF39S)||defined(CONFIG_MACH_MSM8X60_EF40S)||defined(CONFIG_MACH_MSM8X60_EF40K)||defined(CONFIG_MACH_MSM8X60_EF65L)
	TOUCH_IOCTL_READ_FW_VERSION,
#endif
	TOUCH_IOCTL_START_UPDATE,
	TOUCH_IOCTL_SELF_TEST,
#if defined(CONFIG_MACH_MSM8X60_EF33S)||defined(CONFIG_MACH_MSM8X60_EF34C)||defined(CONFIG_MACH_MSM8X60_EF34K)||defined(CONFIG_MACH_MSM8X60_EF35L)
    TOUCH_IOCTL_SET_COLOR,
#elif defined(CONFIG_MACH_MSM8X60_EF39S)||defined(CONFIG_MACH_MSM8X60_EF40S)||defined(CONFIG_MACH_MSM8X60_EF40K)||defined(CONFIG_MACH_MSM8X60_EF65L)
	TOUCH_IOCTL_DIAGNOSTIC_MIN_DEBUG,
	TOUCH_IOCTL_DIAGNOSTIC_MAX_DEBUG,
#endif
    TOUCH_IOCTL_READ_CHIP_REVISION = 2030,
#if defined(CONFIG_MACH_MSM8X60_EF35L)
    TOUCH_IOCTL_READ_FW_VERSION,
#endif
    TOUCH_IOCTL_READ_REG_DATA_VERSION,

	TOUCH_IOCTL_INIT = 3001,	
	TOUCH_IOCTL_OFF  = 3002,
} TOUCH_IOCTL_CMD;



#endif //_TOUCH_IOCTL_H_
